################################################
#                 Server Handler               #
################################################
#   id: doesn't have to be a number it can be  #
#              anything you want.              #
################################################

Server:
    id:
    type: